# Generated by Django 5.0.3 on 2024-04-03 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(default='M', max_length=1)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestry', models.CharField(max_length=250)),
                ('race', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=250)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheArchives.character')),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(max_length=250)),
                ('secrets', models.CharField(max_length=250)),
                ('principles', models.CharField(max_length=250)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheArchives.character')),
            ],
        ),
    ]
